// <auto-generated />
using System;
using KurumiConcursos.Infra.ORM.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KurumiConcursos.Infra.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.AchievementMilestone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics_json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("achievement_milestone", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.AdminProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_profile_user_id");

                    b.ToTable("AdminProfile", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.CalendarEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("creation_date")
                        .HasColumnOrder(7);

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("event_date")
                        .HasColumnOrder(3);

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update_date")
                        .HasColumnOrder(8);

                    b.Property<string>("Note")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("note")
                        .HasColumnOrder(6);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title")
                        .HasColumnOrder(4);

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type")
                        .HasColumnOrder(5);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_calendar_event_user_id");

                    b.ToTable("calendar_event", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.DomainLogger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("Action")
                        .HasColumnType("smallint")
                        .HasColumnName("action")
                        .HasColumnOrder(2);

                    b.Property<DateTimeOffset>("ActionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("action_date")
                        .HasColumnOrder(4);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasColumnOrder(3);

                    b.Property<string>("EntityId")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("entity_id")
                        .HasColumnOrder(6);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("DomainLogger", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.ExamJourney", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CompletedSyllabusCycles")
                        .HasColumnType("integer")
                        .HasColumnName("completed_syllabus_cycles");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("ExamBoard")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("exam_board");

                    b.Property<DateOnly?>("ExamDate")
                        .HasColumnType("date")
                        .HasColumnName("exam_date");

                    b.Property<bool>("IncludeInStatistics")
                        .HasColumnType("boolean")
                        .HasColumnName("include_in_statistics");

                    b.Property<string>("Institution")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("institution");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("NoticeUrl")
                        .HasColumnType("text")
                        .HasColumnName("notice_url");

                    b.Property<int?>("Openings")
                        .HasColumnType("integer")
                        .HasColumnName("openings");

                    b.Property<string>("Position")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("position");

                    b.Property<decimal?>("Salary")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("salary");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("exam_journey", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.FlashCollection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("flash_collection", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.FocusSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id");

                    b.Property<long?>("KnowledgeAreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("knowledge_area_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("StudyDate")
                        .HasColumnType("date")
                        .HasColumnName("study_date");

                    b.Property<long?>("SyllabusNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("syllabus_node_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("focus_session", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Role", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaim", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaim", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.UserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.KnowledgeArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<int?>("ExpectedQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("expected_questions");

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.ToTable("knowledge_area", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MemoryCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("back");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<decimal>("EaseFactor")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("ease_factor");

                    b.Property<long>("FlashCollectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("collection_id");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("front");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("interval_days");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<DateOnly?>("NextReviewOn")
                        .HasColumnType("date")
                        .HasColumnName("next_review_on");

                    b.HasKey("Id");

                    b.HasIndex("FlashCollectionId");

                    b.ToTable("memory_card", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MemoryRecall", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<long>("MemoryCardId")
                        .HasColumnType("bigint")
                        .HasColumnName("memory_card_id");

                    b.Property<int>("NewIntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("new_interval_days");

                    b.Property<int>("PreviousIntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("previous_interval_days");

                    b.HasKey("Id");

                    b.HasIndex("MemoryCardId");

                    b.ToTable("memory_recall", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MockAssessment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AssessmentDate")
                        .HasColumnType("date")
                        .HasColumnName("assessment_date");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<decimal?>("Score")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("score");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("mock_assessment", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MockAssessmentBreakdown", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<long>("KnowledgeAreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("knowledge_area_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<long>("MockAssessmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("mock_assessment_id");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.HasKey("Id");

                    b.HasIndex("MockAssessmentId");

                    b.ToTable("mock_assessment_breakdown", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.PersonalData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age")
                        .HasColumnOrder(6);

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasColumnOrder(8);

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasColumnType("timestamptz")
                        .HasColumnName("date_of_birth")
                        .HasColumnOrder(7);

                    b.Property<string>("Document")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("document")
                        .HasColumnOrder(4);

                    b.Property<string>("FullName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("full_name")
                        .HasColumnOrder(3);

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(9);

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone")
                        .HasColumnOrder(5);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_personal_data_user_id");

                    b.ToTable("PersonalData", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.PracticeEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id");

                    b.Property<long?>("KnowledgeAreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("knowledge_area_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<DateOnly>("PracticeDate")
                        .HasColumnType("date")
                        .HasColumnName("practice_date");

                    b.Property<int>("QuestionsAnswered")
                        .HasColumnType("integer")
                        .HasColumnName("questions_answered");

                    b.Property<long?>("SyllabusNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("syllabus_node_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("practice_entry", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.ReviewAppointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<DateOnly>("ScheduledFor")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_for");

                    b.Property<bool>("Superseded")
                        .HasColumnType("boolean")
                        .HasColumnName("superseded");

                    b.Property<long>("SyllabusNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("syllabus_node_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("review_appointment", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(3);

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(4);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_profile_user_id");

                    b.ToTable("StudentProfile", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.StudyResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<long?>("KnowledgeAreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("knowledge_area_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<long?>("SyllabusNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("syllabus_node_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("study_resource", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.StudyRoutine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active")
                        .HasColumnOrder(6);

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration_json")
                        .HasColumnOrder(7);

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("creation_date")
                        .HasColumnOrder(8);

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id")
                        .HasColumnOrder(3);

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind")
                        .HasColumnOrder(5);

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update_date")
                        .HasColumnOrder(9);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(180)")
                        .HasColumnName("title")
                        .HasColumnOrder(4);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("UserId", "JourneyId")
                        .HasDatabaseName("ix_study_routine_user_journey");

                    b.ToTable("study_routine", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.StudyRoutineBlock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at")
                        .HasColumnOrder(12);

                    b.Property<int>("CompletedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("completed_minutes")
                        .HasColumnOrder(10);

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("creation_date")
                        .HasColumnOrder(13);

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id")
                        .HasColumnOrder(3);

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update_date")
                        .HasColumnOrder(14);

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("display_order")
                        .HasColumnOrder(11);

                    b.Property<int>("PlannedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("planned_minutes")
                        .HasColumnOrder(9);

                    b.Property<DateOnly>("ScheduledFor")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_for")
                        .HasColumnOrder(6);

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasColumnOrder(8);

                    b.Property<long>("StudyRoutineId")
                        .HasColumnType("bigint")
                        .HasColumnName("study_routine_id")
                        .HasColumnOrder(4);

                    b.Property<long>("SyllabusNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("syllabus_node_id")
                        .HasColumnOrder(5);

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type")
                        .HasColumnOrder(7);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ScheduledFor")
                        .HasDatabaseName("ix_study_routine_block_user_date");

                    b.ToTable("study_routine_block", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.SyllabusNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<long>("KnowledgeAreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("knowledge_area_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<DateOnly?>("StudiedOn")
                        .HasColumnType("date")
                        .HasColumnName("studied_on");

                    b.Property<DateOnly?>("StudyStartedOn")
                        .HasColumnType("date")
                        .HasColumnName("study_started_on");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeAreaId");

                    b.HasIndex("ParentId");

                    b.ToTable("syllabus_node", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count")
                        .HasColumnOrder(15);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp")
                        .HasColumnOrder(9);

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date")
                        .HasColumnOrder(19);

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email")
                        .HasColumnOrder(4);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed")
                        .HasColumnOrder(6);

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("identifier")
                        .HasColumnOrder(16);

                    b.Property<DateTimeOffset?>("LastAccessDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_access_date")
                        .HasColumnOrder(20);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled")
                        .HasColumnOrder(14);

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end")
                        .HasColumnOrder(13);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_email")
                        .HasColumnOrder(5);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_username")
                        .HasColumnOrder(3);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash")
                        .HasColumnOrder(7);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone_number")
                        .HasColumnOrder(10);

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed")
                        .HasColumnOrder(11);

                    b.Property<int>("PreferredLanguage")
                        .HasColumnType("integer")
                        .HasColumnName("preferred_language")
                        .HasColumnOrder(18);

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp")
                        .HasColumnOrder(8);

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasColumnOrder(17);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled")
                        .HasColumnOrder(12);

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("username")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ux_user_identifier");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("User", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.AdminProfile", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.User", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("KurumiConcursos.Domain.Entities.AdminProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.ExamJourney", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("ExamJourneys")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.RoleClaim", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.IdentityEntities.Role", null)
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.UserClaim", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.User", null)
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.UserLogin", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.UserRole", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.IdentityEntities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KurumiConcursos.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.UserToken", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.User", null)
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.KnowledgeArea", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.ExamJourney", "Journey")
                        .WithMany("KnowledgeAreas")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MemoryCard", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.FlashCollection", "Collection")
                        .WithMany("Cards")
                        .HasForeignKey("FlashCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MemoryRecall", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.MemoryCard", "Card")
                        .WithMany("Recalls")
                        .HasForeignKey("MemoryCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MockAssessmentBreakdown", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.MockAssessment", "MockAssessment")
                        .WithMany("Breakdown")
                        .HasForeignKey("MockAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MockAssessment");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.PersonalData", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.User", "User")
                        .WithOne("PersonalData")
                        .HasForeignKey("KurumiConcursos.Domain.Entities.PersonalData", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("KurumiConcursos.Domain.Entities.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.SyllabusNode", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.KnowledgeArea", "KnowledgeArea")
                        .WithMany("SyllabusNodes")
                        .HasForeignKey("KnowledgeAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KurumiConcursos.Domain.Entities.SyllabusNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KnowledgeArea");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.ExamJourney", b =>
                {
                    b.Navigation("KnowledgeAreas");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.FlashCollection", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.Role", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.KnowledgeArea", b =>
                {
                    b.Navigation("SyllabusNodes");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MemoryCard", b =>
                {
                    b.Navigation("Recalls");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MockAssessment", b =>
                {
                    b.Navigation("Breakdown");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.StudentProfile", b =>
                {
                    b.Navigation("ExamJourneys");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.SyllabusNode", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.User", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("PersonalData");

                    b.Navigation("StudentProfile");

                    b.Navigation("UserClaims");

                    b.Navigation("UserRoles");

                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
