// <auto-generated />
using System;
using KurumiConcursos.Infra.ORM.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KurumiConcursos.Infra.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.AchievementMilestone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("AchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics_json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("achievement_milestone", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.ExamJourney", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("CompletedSyllabusCycles")
                        .HasColumnType("integer")
                        .HasColumnName("completed_syllabus_cycles");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("ExamBoard")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("exam_board");

                    b.Property<DateOnly?>("ExamDate")
                        .HasColumnType("date")
                        .HasColumnName("exam_date");

                    b.Property<bool>("IncludeInStatistics")
                        .HasColumnType("boolean")
                        .HasColumnName("include_in_statistics");

                    b.Property<string>("Institution")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("institution");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("NoticeUrl")
                        .HasColumnType("text")
                        .HasColumnName("notice_url");

                    b.Property<int?>("Openings")
                        .HasColumnType("integer")
                        .HasColumnName("openings");

                    b.Property<string>("Position")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("position");

                    b.Property<decimal?>("Salary")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("salary");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("exam_journey", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.FlashCollection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("flash_collection", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.FocusSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id");

                    b.Property<long?>("KnowledgeAreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("knowledge_area_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("StudyDate")
                        .HasColumnType("date")
                        .HasColumnName("study_date");

                    b.Property<long?>("SyllabusNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("syllabus_node_id");

                    b.HasKey("Id");

                    b.ToTable("focus_session", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Role", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaim", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaim", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.UserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.KnowledgeArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<int?>("ExpectedQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("expected_questions");

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.ToTable("knowledge_area", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MemoryCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("back");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<decimal>("EaseFactor")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("ease_factor");

                    b.Property<long>("FlashCollectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("collection_id");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("front");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("interval_days");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<DateOnly?>("NextReviewOn")
                        .HasColumnType("date")
                        .HasColumnName("next_review_on");

                    b.HasKey("Id");

                    b.HasIndex("FlashCollectionId");

                    b.ToTable("memory_card", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MemoryRecall", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<long>("MemoryCardId")
                        .HasColumnType("bigint")
                        .HasColumnName("memory_card_id");

                    b.Property<int>("NewIntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("new_interval_days");

                    b.Property<int>("PreviousIntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("previous_interval_days");

                    b.HasKey("Id");

                    b.HasIndex("MemoryCardId");

                    b.ToTable("memory_recall", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MockAssessment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateOnly>("AssessmentDate")
                        .HasColumnType("date")
                        .HasColumnName("assessment_date");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<decimal?>("Score")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("score");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.HasKey("Id");

                    b.ToTable("mock_assessment", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MockAssessmentBreakdown", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<long>("KnowledgeAreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("knowledge_area_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<long>("MockAssessmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("mock_assessment_id");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.HasKey("Id");

                    b.HasIndex("MockAssessmentId");

                    b.ToTable("mock_assessment_breakdown", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.PracticeEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id");

                    b.Property<long?>("KnowledgeAreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("knowledge_area_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<DateOnly>("PracticeDate")
                        .HasColumnType("date")
                        .HasColumnName("practice_date");

                    b.Property<int>("QuestionsAnswered")
                        .HasColumnType("integer")
                        .HasColumnName("questions_answered");

                    b.Property<long?>("SyllabusNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("syllabus_node_id");

                    b.HasKey("Id");

                    b.ToTable("practice_entry", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.ReviewAppointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<DateOnly>("ScheduledFor")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_for");

                    b.Property<bool>("Superseded")
                        .HasColumnType("boolean")
                        .HasColumnName("superseded");

                    b.Property<long>("SyllabusNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("syllabus_node_id");

                    b.HasKey("Id");

                    b.ToTable("review_appointment", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.StudyResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<long?>("KnowledgeAreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("knowledge_area_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<long?>("SyllabusNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("syllabus_node_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("study_resource", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.StudyRoutine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration_json");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<long>("JourneyId")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("study_routine", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.SyllabusNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<long>("KnowledgeAreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("knowledge_area_id");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<DateOnly?>("StudiedOn")
                        .HasColumnType("date")
                        .HasColumnName("studied_on");

                    b.Property<DateOnly?>("StudyStartedOn")
                        .HasColumnType("date")
                        .HasColumnName("study_started_on");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeAreaId");

                    b.HasIndex("ParentId");

                    b.ToTable("syllabus_node", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identifier");

                    b.Property<DateTimeOffset?>("LastAccessDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_access_date");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("PreferredLanguage")
                        .HasColumnType("integer")
                        .HasColumnName("preferred_language");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ux_user_identifier");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("User", "kurumi_concursos");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.ExamJourney", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.User", "Account")
                        .WithMany("ExamJourneys")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.RoleClaim", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.IdentityEntities.Role", null)
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.UserClaim", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.User", null)
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.UserLogin", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.UserRole", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.IdentityEntities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KurumiConcursos.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.UserToken", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.User", null)
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.KnowledgeArea", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.ExamJourney", "Journey")
                        .WithMany("KnowledgeAreas")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MemoryCard", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.FlashCollection", "Collection")
                        .WithMany("Cards")
                        .HasForeignKey("FlashCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MemoryRecall", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.MemoryCard", "Card")
                        .WithMany("Recalls")
                        .HasForeignKey("MemoryCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MockAssessmentBreakdown", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.MockAssessment", "MockAssessment")
                        .WithMany("Breakdown")
                        .HasForeignKey("MockAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MockAssessment");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.SyllabusNode", b =>
                {
                    b.HasOne("KurumiConcursos.Domain.Entities.KnowledgeArea", "KnowledgeArea")
                        .WithMany("SyllabusNodes")
                        .HasForeignKey("KnowledgeAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KurumiConcursos.Domain.Entities.SyllabusNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KnowledgeArea");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.ExamJourney", b =>
                {
                    b.Navigation("KnowledgeAreas");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.FlashCollection", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.IdentityEntities.Role", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.KnowledgeArea", b =>
                {
                    b.Navigation("SyllabusNodes");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MemoryCard", b =>
                {
                    b.Navigation("Recalls");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.MockAssessment", b =>
                {
                    b.Navigation("Breakdown");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.SyllabusNode", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("KurumiConcursos.Domain.Entities.User", b =>
                {
                    b.Navigation("ExamJourneys");

                    b.Navigation("UserClaims");

                    b.Navigation("UserRoles");

                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
